insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("노트북", "컴퓨터", 100, "삼성전자", 10, "최신형")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("운동화", "잡화", 10, "아디다스", 1000, "초경량")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("TV", "가전", 300, "LG전자", 300, "OLED")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("휘센", "에어컨", 130, "LG전자", 50, "스마트")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("갤럭시 s20", "스마트폰", 110, "삼성전자", 200, "자급제")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("청송 사과", "과일", 5, "꿀땡이사과", 500, "부사")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("반팔티", "의류", 20, "나이키", 700, "기능성")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("트레이닝 팬츠", "의류", 15, "휠라", 200, "봄 가을용")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("진라면", "가공식품", 6, "오뚜기", 2000, "매운맛")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("의자", "가구", 50, "시디즈", 60, "메쉬의자")